### ISSUE TITLE
v1.2.20 or later cannot be installed.

### ISSUE THREAD

**Issue by ShiN-K-278** [takamin/mz700-js#179]
v1.2.20 or later cannot be installed. Below is the log.

npm WARN deprecated grunt-contrib-uglify-es@3.3.0: deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/Users/hogehoge/.nvm/versions/node/v12.16.2/bin/mz700-js -> /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js/bin/mz700-web.js
/Users/hogehoge/.nvm/versions/node/v12.16.2/bin/mz700-cli -> /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js/bin/mz700-cli.js
/Users/hogehoge/.nvm/versions/node/v12.16.2/bin/mzasm -> /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js/bin/mzasm.js
/Users/hogehoge/.nvm/versions/node/v12.16.2/bin/mzdas -> /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js/bin/mzdasm.js
/Users/hogehoge/.nvm/versions/node/v12.16.2/bin/bin2mzt -> /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js/bin/bin2mzt.js

> fsevents@1.2.12 install /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js/node_modules/fsevents
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/hogehoge/.nvm/versions/node/v12.16.2/bin/node" "/Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js/node_modules/fsevents
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> core-js@2.6.11 postinstall /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> mz700-js@1.2.21 postinstall /Users/hogehoge/.nvm/versions/node/v12.16.2/lib/node_modules/mz700-js
> grunt release

Running "ts:default" (ts) task
Compiling...
Using tsc v3.8.3

TypeScript compilation complete: 7.01s for 60 TypeScript files.

Running "eslint:target" (eslint) task

Running "browserify:build" (browserify) task
>> Bundle ./build/bundle-mz700-worker.js created.
>> Bundle ./build/bundle-mz700-emu.js created.

Running "uglify:build" (uglify) task
>> 2 files created 1.57 MB → 708.15 kB

Running "copy:release" (copy) task
Copied 3 files

Done.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/mz700-js/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ mz700-js@1.2.21
added 589 packages from 1299 contributors in 64.602s

**Comment by ShiN-K-278** [comment]
The 'gyp: No Xcode or CLT version detected! ' error has been resolved and installed successfully. However, the emulator screen does not appear.
There is only one character "." On the tab screen of the browser.
I can revert to the 1.2.19 backup to use it.

**Comment by ShiN-K-278** [comment]
It worked on 1.2.24.
