### ISSUE TITLE
Node.js emulator (using WebSocket) could not load the MZT or M12 file that is dropped on the screen

### ISSUE THREAD

**Issue by takamin** [takamin/mz700-js#203]
Node.js printsfollowing stack trace to console, when drop a file.
Full WebApp emulator works.

>```
>$ npm run mz700-ws
>
>> mz700-js@1.4.3 mz700-ws /home/takami/Git/mz700-js
>> node bin/mz700-ws.js
>
>The WebSocket-Version MZ-700 Emulator. -- mz700-js@1.4.3
>*** exception:  TypeError: bytes.slice is not a function
>    at Function.fromBytes (/home/takami/Git/mz700-js/lib/mz-tape.js:256:59)
>    at MZ700.dataRecorder_setCmt (/home/takami/Git/mz700-js/MZ-700/mz700.js:523:25)
>    at MZ700.setCassetteTape (/home/takami/Git/mz700-js/MZ-700/mz700.js:352:10)
>    at WebSocketServer.TransWorker.onReceiveClientMessage (/home/takami/Git/mz700-js/node_modules/transworker/lib/transworker.js:357:51)
>    at WebSocket.transworker.messagePort.onmessage (/home/takami/Git/mz700-js/node_modules/transworker/lib/websocket-server.js:23:29)
>    at WebSocket.onMessage (/home/takami/Git/mz700-js/node_modules/ws/lib/event-target.js:125:16)
>    at WebSocket.emit (events.js:315:20)
>    at Receiver.receiverOnMessage (/home/takami/Git/mz700-js/node_modules/ws/lib/websocket.js:797:20)
>    at Receiver.emit (events.js:315:20)
>    at Receiver.dataMessage (/home/takami/Git/mz700-js/node_modules/ws/lib/receiver.js:437:14) in method setCassetteTape params: [{"0":1,"1":83,"2":73,"3":68 ...
>```

**Comment by takamin** [comment]
The parameter `bytes` of the method `MZTape.fromBytes(bytes)` is an instance of `Object` when it's in a context of Node.js. In a browser context, it is an instance of `Array`.
